version: "3.9"
services:
  app:
    image: localhost/mailttr:dev
    container_name: MaiLttrDev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: mailttr
    tty: true
    networks:
      - mailttr
    volumes:
      - ..:/usr/local/mailttr/src
    environment:
      - TZ=Asia/Tokyo
      - EDITOR=vi
networks:
  mailttr:
volumes:
  mailttr: