version: "3.9"
services:
  app:
    image: localhost/mailetter:dev
    container_name: MaiLetterApp
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: mailetter
    tty: true
    networks:
      - mailetter
    volumes:
      - type: bind
        source: ..
        target: /usr/local/mailetter/src
    environment:
      - TZ=Asia/Tokyo
      - EDITOR=vi
networks:
  mailetter:
volumes:
  mailetter: