version: "3.3"
services:
  app:
    image: tsukinoha.com/mailetter:dev
    container_name: MaiLetterApp
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: mailetter
    tty: true
    networks:
      - mailetter
    volumes:
      - type: bind
        source: ..
        target: /usr/local/mailetter/src
    environment:
      - TZ=Asia/Tokyo
      - EDITOR=vi
networks:
  mailetter:
volumes:
  mailetter: