version: "3.9"
services:
  app:
    image: localhost/mailetter:dev
    container_name: MaiLetterDev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: mailetter
    tty: true
    networks:
      - mailetter
    volumes:
      - ..:/usr/local/mailetter/src
    environment:
      - TZ=Asia/Tokyo
      - EDITOR=vi
networks:
  mailetter:
volumes:
  mailetter: